server:
  port: 8080
  servlet:
    context-path: /manage
spring:
  thymeleaf:
    cache: false
  datasource:
    # url: jdbc:p6spy:mysql://localhost:3306/yacht_mall?serverTimezone=GMT%2B8&useUnicode=true&useSSL=false&characterEncoding=utf8
    url: jdbc:p6spy:mysql://localhost:3306/yacht_mall?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jackson:
      date-format : yyyy-MM-dd HH:mm:ss
      joda-date-time-format : yyyy-MM-dd HH:mm:ss